<?php
/**
 * COVE dummy product definitions for the demo importer.
 * Returns an array of product data arrays.
 * @package COVE
 */
defined( 'ABSPATH' ) || exit;

function cove_dummy_products(): array {
	return array(
		// Kitchen — New
		array(
			'name'       => 'Espresso Coffee Machine 15-bar',
			'price'      => 1299,
			'rrp'        => 1299,
			'condition'  => 'new',
			'cat'        => 'kitchen',
			'brand'      => 'Breville',
			'warranty'   => '2 years',
			'energy'     => 'A',
			'colour'     => 'Stainless Steel',
			'dims'       => '280 × 320 × 340mm',
			'weight'     => 4.2,
			'grade_note' => '',
			'desc'       => 'Professional 15-bar pressure system. Built-in grinder, steam wand, and 2L water tank.',
		),
		array(
			'name'       => 'Variable Temp Kettle 1.7L',
			'price'      => 499,
			'rrp'        => 499,
			'condition'  => 'new',
			'cat'        => 'kitchen',
			'brand'      => 'Russell Hobbs',
			'warranty'   => '2 years',
			'energy'     => 'A+',
			'colour'     => 'Pearl White',
			'dims'       => '220 × 150 × 250mm',
			'weight'     => 1.1,
			'grade_note' => '',
			'desc'       => '5 preset temperatures from 60°C to 100°C. Keep-warm function for 30 minutes.',
		),
		array(
			'name'       => 'Air Fryer 5.5L XXL',
			'price'      => 899,
			'rrp'        => 899,
			'condition'  => 'new',
			'cat'        => 'kitchen',
			'brand'      => 'Philips',
			'warranty'   => '2 years',
			'energy'     => 'A++',
			'colour'     => 'Black',
			'dims'       => '310 × 390 × 380mm',
			'weight'     => 5.8,
			'grade_note' => '',
			'desc'       => 'Twin TurboStar technology. Up to 90% less fat. Digital touchscreen.',
		),
		// Kitchen — Grade A
		array(
			'name'       => 'Stand Mixer 800W',
			'price'      => 1999,
			'rrp'        => 2699,
			'condition'  => 'grade-a',
			'cat'        => 'kitchen',
			'brand'      => 'KitchenAid',
			'warranty'   => '12 months',
			'energy'     => 'A',
			'colour'     => 'Empire Red',
			'dims'       => '230 × 360 × 350mm',
			'weight'     => 11.3,
			'grade_note' => 'Open box — returned unused. Original packaging, all attachments included. No cosmetic marks.',
			'desc'       => '800W motor with 10-speed control. Includes flat beater, dough hook and wire whisk.',
		),
		// Kitchen — Grade B
		array(
			'name'       => 'Microwave 30L Convection',
			'price'      => 1099,
			'rrp'        => 1799,
			'condition'  => 'grade-b',
			'cat'        => 'kitchen',
			'brand'      => 'Samsung',
			'warranty'   => '90 days',
			'energy'     => 'A+',
			'colour'     => 'Inox',
			'dims'       => '520 × 406 × 310mm',
			'weight'     => 13.5,
			'grade_note' => 'Small scratch on left side panel — not visible when installed under a counter. Functionality 100%.',
			'desc'       => '30L capacity. Convection + grill + microwave combination. Auto-cook programs.',
		),
		// Kitchen — Grade C
		array(
			'name'       => 'Blender 2L Pro Series',
			'price'      => 549,
			'rrp'        => 1199,
			'condition'  => 'grade-c',
			'cat'        => 'kitchen',
			'brand'      => 'Vitamix',
			'warranty'   => '90 days',
			'energy'     => 'A',
			'colour'     => 'Black',
			'dims'       => '200 × 200 × 450mm',
			'weight'     => 5.4,
			'grade_note' => 'Dent on right side of base. Lid handle has minor crack (functional). Motor and blades work perfectly.',
			'desc'       => '2L container. 6 hardened stainless-steel blades. 10 variable speeds + pulse.',
		),
		// Laundry — New
		array(
			'name'       => 'Front Loader Washing Machine 8kg',
			'price'      => 6999,
			'rrp'        => 6999,
			'condition'  => 'new',
			'cat'        => 'laundry',
			'brand'      => 'Samsung',
			'warranty'   => '2 years',
			'energy'     => 'A+++',
			'colour'     => 'White',
			'dims'       => '600 × 550 × 845mm',
			'weight'     => 71,
			'grade_note' => '',
			'desc'       => 'EcoBubble technology. 1400 RPM spin. 15 wash programmes. Child lock.',
		),
		// Laundry — Grade B
		array(
			'name'       => 'Front Loader 7kg',
			'price'      => 3999,
			'rrp'        => 6499,
			'condition'  => 'grade-b',
			'cat'        => 'laundry',
			'brand'      => 'LG',
			'warranty'   => '90 days',
			'energy'     => 'A++',
			'colour'     => 'White',
			'dims'       => '600 × 550 × 845mm',
			'weight'     => 68,
			'grade_note' => 'Scuff mark on top panel — invisible when in position. Drum, motor and all wash programmes fully functional.',
			'desc'       => '7kg capacity. 6 Motion technology. 1400 RPM. Turbowash60.',
		),
		// Laundry — Grade C
		array(
			'name'       => 'Top Loader 12kg',
			'price'      => 2499,
			'rrp'        => 5599,
			'condition'  => 'grade-c',
			'cat'        => 'laundry',
			'brand'      => 'Defy',
			'warranty'   => '90 days',
			'energy'     => 'A+',
			'colour'     => 'White',
			'dims'       => '550 × 555 × 1030mm',
			'weight'     => 44,
			'grade_note' => 'Visible dent on back panel and light rust spotting on lid hinge. All wash functions work correctly. Ideal for utility room.',
			'desc'       => '12kg capacity. 8 wash programmes. Delay start. Anti-bacterial tub.',
		),
		// Climate — New
		array(
			'name'       => 'Air Purifier 45m² HEPA',
			'price'      => 2199,
			'rrp'        => 2199,
			'condition'  => 'new',
			'cat'        => 'climate',
			'brand'      => 'Xiaomi',
			'warranty'   => '2 years',
			'energy'     => 'A++',
			'colour'     => 'White',
			'dims'       => '240 × 240 × 520mm',
			'weight'     => 4.8,
			'grade_note' => '',
			'desc'       => 'True HEPA H13 filter. Covers 45m². PM2.5 sensor. App controlled. Ultra-quiet 30dB.',
		),
		// Climate — Grade A
		array(
			'name'       => 'Tower Fan 40" with Remote',
			'price'      => 799,
			'rrp'        => 1099,
			'condition'  => 'grade-a',
			'cat'        => 'climate',
			'brand'      => 'Dyson',
			'warranty'   => '12 months',
			'energy'     => 'A+++',
			'colour'     => 'Black/Nickel',
			'dims'       => '150 × 150 × 1030mm',
			'weight'     => 3.0,
			'grade_note' => 'Open box, never used. Display model removed from packaging for customer demonstration only.',
			'desc'       => 'Air Multiplier technology. 10 airflow settings. Sleep timer. Oscillation 90°.',
		),
		// Floor Care — New
		array(
			'name'       => 'Robot Vacuum & Mop 4500Pa',
			'price'      => 4299,
			'rrp'        => 4299,
			'condition'  => 'new',
			'cat'        => 'floor-care',
			'brand'      => 'Roborock',
			'warranty'   => '2 years',
			'energy'     => 'A+',
			'colour'     => 'White',
			'dims'       => '353 × 353 × 96mm',
			'weight'     => 3.5,
			'grade_note' => '',
			'desc'       => 'LiDAR navigation. 4500Pa suction. Auto-empty dock. Mop with intelligent water control.',
		),
		// Floor Care — Grade B
		array(
			'name'       => 'Cordless Stick Vacuum 750W',
			'price'      => 899,
			'rrp'        => 1699,
			'condition'  => 'grade-b',
			'cat'        => 'floor-care',
			'brand'      => 'Dyson',
			'warranty'   => '90 days',
			'energy'     => 'A',
			'colour'     => 'Nickel/Blue',
			'dims'       => '250 × 210 × 1145mm',
			'weight'     => 2.6,
			'grade_note' => 'Light scratch on handle. Suction, battery, all attachments work perfectly. 40-min runtime confirmed.',
			'desc'       => '40-minute fade-free runtime. Whole-machine HEPA filtration. 5-layer filtration.',
		),
		// Personal Care — New
		array(
			'name'       => 'Professional Hair Dryer 2400W',
			'price'      => 699,
			'rrp'        => 699,
			'condition'  => 'new',
			'cat'        => 'personal-care',
			'brand'      => 'Remington',
			'warranty'   => '2 years',
			'energy'     => 'A',
			'colour'     => 'Rose Gold',
			'dims'       => '220 × 65 × 280mm',
			'weight'     => 0.58,
			'grade_note' => '',
			'desc'       => '2400W AC motor. Ionic technology. 3 heat + 2 speed settings. Cool shot button.',
		),
		// Personal Care — Grade A
		array(
			'name'       => 'Electric Shaver Series 9',
			'price'      => 1599,
			'rrp'        => 2299,
			'condition'  => 'grade-a',
			'cat'        => 'personal-care',
			'brand'      => 'Braun',
			'warranty'   => '12 months',
			'energy'     => 'A',
			'colour'     => 'Silver/Black',
			'dims'       => '60 × 55 × 190mm',
			'weight'     => 0.19,
			'grade_note' => 'Open box. Used once for demo. Fully cleaned, heads replaced. Indistinguishable from new.',
			'desc'       => 'Series 9 Pro. 5-sync foil system. AutoSense motor. 60 min battery. Wet & dry.',
		),
		// Personal Care — Grade C
		array(
			'name'       => 'Cordless Hair Straightener',
			'price'      => 399,
			'rrp'        => 899,
			'condition'  => 'grade-c',
			'cat'        => 'personal-care',
			'brand'      => 'GHD',
			'warranty'   => '90 days',
			'energy'     => 'A',
			'colour'     => 'Black',
			'dims'       => '50 × 40 × 290mm',
			'weight'     => 0.44,
			'grade_note' => 'Scuff marks on plates surround and faded logo on one plate. Plates are undamaged and heat to correct temperature. Battery holds full charge.',
			'desc'       => 'Cordless ceramic plates. USB-C charging. 185°C in under 30 seconds. 30-min auto-off.',
		),
	);
}
